export const SET_START_TIME = 'SET_START_TIME';
export const SET_CORRECT_ANSWERS = 'SET_CORRECT_ANSWERS';
export const SET_TOTAL_QUESTIONS = 'SET_TOTAL_QUESTIONS';
export const SET_END_TIME = 'SET_END_TIME';
export const SET_WRONG_ANSWERS = 'SET_WRONG_ANSWERS';
export const RESET_QUIZ = 'RESET_QUIZ';